import { StyleSheet, Dimensions } from "react-native";
const {width,height} = Dimensions.get('window');

const styles = StyleSheet.create({
    contentFullScreen:{
        position:'absolute',
        height:width,
        width:height,
        justifyContent:'flex-end',
    },
    btnContainer:{
        height:width,
        width:height,
        position:'absolute',
        justifyContent:'center',
        alignItems:'center',
    },
    btnList:{
        height:width/3.5,
        width:height,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    pouseWrapper:{
        height:width/3.5,
        width:width/3.5,
        borderRadius:100,
        backgroundColor:'#00000063',
        justifyContent:'center',
        alignItems:'center',
    },
    centerIcon1:{
        width:(width/3.5)-60,
        height:(width/3.5)-60,
        marginLeft:5,
        resizeMode:'contain',
        zIndex:2
    },
    centerIcon0:{
        width:(width/3.5)-60,
        height:(width/3.5)-60,
        resizeMode:'contain',
        zIndex:2
    },
    skip:{
        width:(width/3.5)-80,
        height:(width/3.5)-80,
    },
    bottomInfo:{
        width:'95%',
        marginLeft:20,
        height:60,
        justifyContent:'space-between',
        flexDirection:'row',

    },
    bottomInfoItem:{
        width:'48%',
        height:60,
        flexDirection:'row'
    },
    bottomInfoItem2:{
        width:'48%',
        height:60,
        flexDirection:'row-reverse',
        
    },
    iconWrapper:{
        height:60,
        width:60*1.33,
        borderRadius:7,
        overflow:'hidden',
        zIndex:2,
        alignItems:'flex-end'
    },
    iconWrapper2:{
        height:60,
        width:60*1.33,
        borderRadius:7,
        overflow:'hidden',
        zIndex:2,
    },
    icon:{
        height:60,
        width:60*1.33,
        borderRadius:7,
        overflow:'hidden',
        position:'absolute',
        zIndex:1
    },
    leftIcon:{
        width:30,
        height:20,
        zIndex:2,
        marginTop:5,
        marginRight:5
    },
    
    textBlock:{
        marginHorizontal:10,
        height:60,
        justifyContent:'space-around'
    },
    time:{
        color:'#fff',
        fontSize:16
    },
    nameProgram:{
        color:'#fff',
        fontSize:16,
        fontWeight:'bold'
    },
    bottomContainer:{
        backgroundColor:'#00000063',
        paddingTop:5
    },
    timeInfo:{
        width:'95%',
        marginLeft:20,
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center' 
    },
    rotate:{
        width:20,
        height:20,
    },
    topContainer:{
        justifyContent:'center',
        flexDirection:'row',
        height:60
    },
    liveBlock:{
        width:100,
        height:34,
        position:'absolute',
        right:10,
        top:10,
    },
    liveIcon:{
        width:'100%',
        height:'100%'
    },
    skipBlock:{
        width:width/2,
        height:width,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'red'
        
    },
    leftSkip:{
        width:60,
        height:50,
        resizeMode:'contain'
    },
    sec:{
        color:'#fff'
    }
});

export default styles
  