import { StyleSheet, Dimensions } from "react-native";
const {width,height} = Dimensions.get('window');
const styles = StyleSheet.create({
    wrapper:{
        flex:1,
        backgroundColor:'#010101'
    },
    movieContainer:{
        height:width/1.777,
        width,
        zIndex:2,
        position:'absolute',
    },
    image:{
        height:width/1.777,
        width,
        resizeMode:'cover',
        justifyContent:'flex-end'
    },
    pouseWrapper:{
        height:width/(1.77*3),
        width:width/(1.77*3),
        borderRadius:100,
        backgroundColor:'#00000063',
        justifyContent:'center',
        alignItems:'center',
        marginHorizontal:40,
        zIndex:3
    },
    centerIcon1:{
        width:width/(1.77*3)-40,
        height:width/(1.77*3)-40,
        marginLeft:5,
        resizeMode:'contain',
        zIndex:2
    },
    center:{
        height:width/1.777,
        width,
        position:'absolute',
        zIndex:3,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    rating:{
        flexDirection:'row',
        justifyContent:'center',
        marginBottom:10,
        zIndex:3
    },
    ratingItem:{
        flexDirection:'row',
        alignItems:'center',
        marginRight:10,
    },
    ratingText:{
        color:'#fff',
        fontSize:20
    },
    ratingIcon:{
        width:40,
        height:40,
        marginRight:10
    },
    contentBtns:{
        width:width-20,
        marginLeft:10,
        flexDirection:'row',
        marginTop:30,
        justifyContent:'center'
    },
    login:{
        paddingVertical:10,
        paddingHorizontal:20,
        backgroundColor:'#E41A4B',
        borderRadius:7
    },
    loginText:{
        color:'#fff',
        fontSize:22,
        fontWeight:'bold',
        marginTop:-5
    },
    itemContent:{
        borderRadius:31,
        overflow:'hidden',
        padding:15,
        backgroundColor:'#474747',
        flexDirection:'row',
    },
    fovoriteText:{
        color:'#BCBCBC',
        fontSize:16
    },
    fovoriteIcon:{
        width:20,
        height:25,
        resizeMode:'contain',
        marginRight:10
    },
    textBlock:{
        width:width-20,
        marginLeft:10,
        marginTop:20,
    },
    title:{
        color:'#fff',
        fontSize:24,
        fontWeight:'bold',
        
    },
    desc:{
        color:'#fff',
        fontSize:16,
        marginTop:20,
        textAlign:'justify'
    },
    trailerBlock:{
        padding:10,
        position:'absolute',
        backgroundColor:'#E41A4B',
        top:10,
        right:10,
        borderRadius:100,
        flexDirection:'row'
    },
    trailerText:{
        color:'#fff'
    },
    serialsBlock:{
        marginTop:20
    },

});

export default styles
  